# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_s6fits', [dirname(__file__)])
        except ImportError:
            import _s6fits
            return _s6fits
        if fp is not None:
            try:
                _mod = imp.load_module('_s6fits', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _s6fits = swig_import_helper()
    del swig_import_helper
else:
    import _s6fits
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


import collections
class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _s6fits.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _s6fits.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _s6fits.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _s6fits.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _s6fits.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _s6fits.SwigPyIterator_equal(self, x)

    def copy(self):
        return _s6fits.SwigPyIterator_copy(self)

    def next(self):
        return _s6fits.SwigPyIterator_next(self)

    def __next__(self):
        return _s6fits.SwigPyIterator___next__(self)

    def previous(self):
        return _s6fits.SwigPyIterator_previous(self)

    def advance(self, n):
        return _s6fits.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _s6fits.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _s6fits.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _s6fits.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _s6fits.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _s6fits.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _s6fits.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _s6fits.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class s6hits_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, s6hits_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, s6hits_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["julian_date"] = _s6fits.s6hits_t_julian_date_set
    __swig_getmethods__["julian_date"] = _s6fits.s6hits_t_julian_date_get
    if _newclass:
        julian_date = _swig_property(_s6fits.s6hits_t_julian_date_get, _s6fits.s6hits_t_julian_date_set)
    __swig_setmethods__["unix_time"] = _s6fits.s6hits_t_unix_time_set
    __swig_getmethods__["unix_time"] = _s6fits.s6hits_t_unix_time_get
    if _newclass:
        unix_time = _swig_property(_s6fits.s6hits_t_unix_time_get, _s6fits.s6hits_t_unix_time_set)
    __swig_setmethods__["ra"] = _s6fits.s6hits_t_ra_set
    __swig_getmethods__["ra"] = _s6fits.s6hits_t_ra_get
    if _newclass:
        ra = _swig_property(_s6fits.s6hits_t_ra_get, _s6fits.s6hits_t_ra_set)
    __swig_setmethods__["bors"] = _s6fits.s6hits_t_bors_set
    __swig_getmethods__["bors"] = _s6fits.s6hits_t_bors_get
    if _newclass:
        bors = _swig_property(_s6fits.s6hits_t_bors_get, _s6fits.s6hits_t_bors_set)
    __swig_setmethods__["dec"] = _s6fits.s6hits_t_dec_set
    __swig_getmethods__["dec"] = _s6fits.s6hits_t_dec_get
    if _newclass:
        dec = _swig_property(_s6fits.s6hits_t_dec_get, _s6fits.s6hits_t_dec_set)
    __swig_setmethods__["nhits"] = _s6fits.s6hits_t_nhits_set
    __swig_getmethods__["nhits"] = _s6fits.s6hits_t_nhits_get
    if _newclass:
        nhits = _swig_property(_s6fits.s6hits_t_nhits_get, _s6fits.s6hits_t_nhits_set)
    __swig_setmethods__["missedpk"] = _s6fits.s6hits_t_missedpk_set
    __swig_getmethods__["missedpk"] = _s6fits.s6hits_t_missedpk_get
    if _newclass:
        missedpk = _swig_property(_s6fits.s6hits_t_missedpk_get, _s6fits.s6hits_t_missedpk_set)
    __swig_setmethods__["detected_power"] = _s6fits.s6hits_t_detected_power_set
    __swig_getmethods__["detected_power"] = _s6fits.s6hits_t_detected_power_get
    if _newclass:
        detected_power = _swig_property(_s6fits.s6hits_t_detected_power_get, _s6fits.s6hits_t_detected_power_set)
    __swig_setmethods__["mean_power"] = _s6fits.s6hits_t_mean_power_set
    __swig_getmethods__["mean_power"] = _s6fits.s6hits_t_mean_power_get
    if _newclass:
        mean_power = _swig_property(_s6fits.s6hits_t_mean_power_get, _s6fits.s6hits_t_mean_power_set)
    __swig_setmethods__["fine_channel_bin"] = _s6fits.s6hits_t_fine_channel_bin_set
    __swig_getmethods__["fine_channel_bin"] = _s6fits.s6hits_t_fine_channel_bin_get
    if _newclass:
        fine_channel_bin = _swig_property(_s6fits.s6hits_t_fine_channel_bin_get, _s6fits.s6hits_t_fine_channel_bin_set)
    __swig_setmethods__["coarse_channel_bin"] = _s6fits.s6hits_t_coarse_channel_bin_set
    __swig_getmethods__["coarse_channel_bin"] = _s6fits.s6hits_t_coarse_channel_bin_get
    if _newclass:
        coarse_channel_bin = _swig_property(_s6fits.s6hits_t_coarse_channel_bin_get, _s6fits.s6hits_t_coarse_channel_bin_set)
    __swig_setmethods__["ifreq"] = _s6fits.s6hits_t_ifreq_set
    __swig_getmethods__["ifreq"] = _s6fits.s6hits_t_ifreq_get
    if _newclass:
        ifreq = _swig_property(_s6fits.s6hits_t_ifreq_get, _s6fits.s6hits_t_ifreq_set)
    __swig_setmethods__["rfreq"] = _s6fits.s6hits_t_rfreq_set
    __swig_getmethods__["rfreq"] = _s6fits.s6hits_t_rfreq_get
    if _newclass:
        rfreq = _swig_property(_s6fits.s6hits_t_rfreq_get, _s6fits.s6hits_t_rfreq_set)

    def __init__(self):
        this = _s6fits.new_s6hits_t()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _s6fits.delete_s6hits_t
    __del__ = lambda self: None
s6hits_t_swigregister = _s6fits.s6hits_t_swigregister
s6hits_t_swigregister(s6hits_t)

class s6dataspec_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, s6dataspec_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, s6dataspec_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["filename"] = _s6fits.s6dataspec_t_filename_set
    __swig_getmethods__["filename"] = _s6fits.s6dataspec_t_filename_get
    if _newclass:
        filename = _swig_property(_s6fits.s6dataspec_t_filename_get, _s6fits.s6dataspec_t_filename_set)
    __swig_setmethods__["seconds"] = _s6fits.s6dataspec_t_seconds_set
    __swig_getmethods__["seconds"] = _s6fits.s6dataspec_t_seconds_get
    if _newclass:
        seconds = _swig_property(_s6fits.s6dataspec_t_seconds_get, _s6fits.s6dataspec_t_seconds_set)
    __swig_setmethods__["s6hits"] = _s6fits.s6dataspec_t_s6hits_set
    __swig_getmethods__["s6hits"] = _s6fits.s6dataspec_t_s6hits_get
    if _newclass:
        s6hits = _swig_property(_s6fits.s6dataspec_t_s6hits_get, _s6fits.s6dataspec_t_s6hits_set)
    __swig_setmethods__["sortby_freq"] = _s6fits.s6dataspec_t_sortby_freq_set
    __swig_getmethods__["sortby_freq"] = _s6fits.s6dataspec_t_sortby_freq_get
    if _newclass:
        sortby_freq = _swig_property(_s6fits.s6dataspec_t_sortby_freq_get, _s6fits.s6dataspec_t_sortby_freq_set)
    __swig_setmethods__["sortby_time"] = _s6fits.s6dataspec_t_sortby_time_set
    __swig_getmethods__["sortby_time"] = _s6fits.s6dataspec_t_sortby_time_get
    if _newclass:
        sortby_time = _swig_property(_s6fits.s6dataspec_t_sortby_time_get, _s6fits.s6dataspec_t_sortby_time_set)
    __swig_setmethods__["sortby_bors"] = _s6fits.s6dataspec_t_sortby_bors_set
    __swig_getmethods__["sortby_bors"] = _s6fits.s6dataspec_t_sortby_bors_get
    if _newclass:
        sortby_bors = _swig_property(_s6fits.s6dataspec_t_sortby_bors_get, _s6fits.s6dataspec_t_sortby_bors_set)
    __swig_setmethods__["threshold"] = _s6fits.s6dataspec_t_threshold_set
    __swig_getmethods__["threshold"] = _s6fits.s6dataspec_t_threshold_get
    if _newclass:
        threshold = _swig_property(_s6fits.s6dataspec_t_threshold_get, _s6fits.s6dataspec_t_threshold_set)
    __swig_setmethods__["bors"] = _s6fits.s6dataspec_t_bors_set
    __swig_getmethods__["bors"] = _s6fits.s6dataspec_t_bors_get
    if _newclass:
        bors = _swig_property(_s6fits.s6dataspec_t_bors_get, _s6fits.s6dataspec_t_bors_set)
    __swig_setmethods__["channels"] = _s6fits.s6dataspec_t_channels_set
    __swig_getmethods__["channels"] = _s6fits.s6dataspec_t_channels_get
    if _newclass:
        channels = _swig_property(_s6fits.s6dataspec_t_channels_get, _s6fits.s6dataspec_t_channels_set)
    __swig_setmethods__["errorcode"] = _s6fits.s6dataspec_t_errorcode_set
    __swig_getmethods__["errorcode"] = _s6fits.s6dataspec_t_errorcode_get
    if _newclass:
        errorcode = _swig_property(_s6fits.s6dataspec_t_errorcode_get, _s6fits.s6dataspec_t_errorcode_set)

    def __init__(self):
        this = _s6fits.new_s6dataspec_t()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _s6fits.delete_s6dataspec_t
    __del__ = lambda self: None
s6dataspec_t_swigregister = _s6fits.s6dataspec_t_swigregister
s6dataspec_t_swigregister(s6dataspec_t)


def get_s6data(s6dataspec):
    return _s6fits.get_s6data(s6dataspec)
get_s6data = _s6fits.get_s6data

def get_time_over_file(filename):
    return _s6fits.get_time_over_file(filename)
get_time_over_file = _s6fits.get_time_over_file

def get_hits_over_file(filename):
    return _s6fits.get_hits_over_file(filename)
get_hits_over_file = _s6fits.get_hits_over_file

def print_hits_structure(s6hits):
    return _s6fits.print_hits_structure(s6hits)
print_hits_structure = _s6fits.print_hits_structure

def print_hits_table(s6hits):
    return _s6fits.print_hits_table(s6hits)
print_hits_table = _s6fits.print_hits_table
class s6Vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, s6Vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, s6Vector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _s6fits.s6Vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _s6fits.s6Vector___nonzero__(self)

    def __bool__(self):
        return _s6fits.s6Vector___bool__(self)

    def __len__(self):
        return _s6fits.s6Vector___len__(self)

    def pop(self):
        return _s6fits.s6Vector_pop(self)

    def __getslice__(self, i, j):
        return _s6fits.s6Vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _s6fits.s6Vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _s6fits.s6Vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _s6fits.s6Vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _s6fits.s6Vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _s6fits.s6Vector___setitem__(self, *args)

    def append(self, x):
        return _s6fits.s6Vector_append(self, x)

    def empty(self):
        return _s6fits.s6Vector_empty(self)

    def size(self):
        return _s6fits.s6Vector_size(self)

    def clear(self):
        return _s6fits.s6Vector_clear(self)

    def swap(self, v):
        return _s6fits.s6Vector_swap(self, v)

    def get_allocator(self):
        return _s6fits.s6Vector_get_allocator(self)

    def begin(self):
        return _s6fits.s6Vector_begin(self)

    def end(self):
        return _s6fits.s6Vector_end(self)

    def rbegin(self):
        return _s6fits.s6Vector_rbegin(self)

    def rend(self):
        return _s6fits.s6Vector_rend(self)

    def pop_back(self):
        return _s6fits.s6Vector_pop_back(self)

    def erase(self, *args):
        return _s6fits.s6Vector_erase(self, *args)

    def __init__(self, *args):
        this = _s6fits.new_s6Vector(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _s6fits.s6Vector_push_back(self, x)

    def front(self):
        return _s6fits.s6Vector_front(self)

    def back(self):
        return _s6fits.s6Vector_back(self)

    def assign(self, n, x):
        return _s6fits.s6Vector_assign(self, n, x)

    def resize(self, *args):
        return _s6fits.s6Vector_resize(self, *args)

    def insert(self, *args):
        return _s6fits.s6Vector_insert(self, *args)

    def reserve(self, n):
        return _s6fits.s6Vector_reserve(self, n)

    def capacity(self):
        return _s6fits.s6Vector_capacity(self)
    __swig_destroy__ = _s6fits.delete_s6Vector
    __del__ = lambda self: None
s6Vector_swigregister = _s6fits.s6Vector_swigregister
s6Vector_swigregister(s6Vector)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _s6fits.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _s6fits.IntVector___nonzero__(self)

    def __bool__(self):
        return _s6fits.IntVector___bool__(self)

    def __len__(self):
        return _s6fits.IntVector___len__(self)

    def pop(self):
        return _s6fits.IntVector_pop(self)

    def __getslice__(self, i, j):
        return _s6fits.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _s6fits.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _s6fits.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _s6fits.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _s6fits.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _s6fits.IntVector___setitem__(self, *args)

    def append(self, x):
        return _s6fits.IntVector_append(self, x)

    def empty(self):
        return _s6fits.IntVector_empty(self)

    def size(self):
        return _s6fits.IntVector_size(self)

    def clear(self):
        return _s6fits.IntVector_clear(self)

    def swap(self, v):
        return _s6fits.IntVector_swap(self, v)

    def get_allocator(self):
        return _s6fits.IntVector_get_allocator(self)

    def begin(self):
        return _s6fits.IntVector_begin(self)

    def end(self):
        return _s6fits.IntVector_end(self)

    def rbegin(self):
        return _s6fits.IntVector_rbegin(self)

    def rend(self):
        return _s6fits.IntVector_rend(self)

    def pop_back(self):
        return _s6fits.IntVector_pop_back(self)

    def erase(self, *args):
        return _s6fits.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _s6fits.new_IntVector(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _s6fits.IntVector_push_back(self, x)

    def front(self):
        return _s6fits.IntVector_front(self)

    def back(self):
        return _s6fits.IntVector_back(self)

    def assign(self, n, x):
        return _s6fits.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _s6fits.IntVector_resize(self, *args)

    def insert(self, *args):
        return _s6fits.IntVector_insert(self, *args)

    def reserve(self, n):
        return _s6fits.IntVector_reserve(self, n)

    def capacity(self):
        return _s6fits.IntVector_capacity(self)
    __swig_destroy__ = _s6fits.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _s6fits.IntVector_swigregister
IntVector_swigregister(IntVector)

# This file is compatible with both classic and new-style classes.


